name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build application
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/ollama-lens-linux-amd64 main.go
          GOOS=darwin GOARCH=arm64 go build -o dist/ollama-lens-macos-arm64 main.go
          GOOS=windows GOARCH=amd64 go build -o dist/ollama-lens-windows-amd64.exe main.go
          GOOS=linux GOARCH=arm64 go build -o dist/ollama-lens-linux-arm64 main.go
          GOOS=windows GOARCH=arm64 go build -o dist/ollama-lens-windows-arm64 main.go
          GOOS=darwin GOARCH=amd64 go build -o dist/ollama-lens-macos-amd64 main.go

      - name: Package artifacts
        run: |
          cd $GITHUB_WORKSPACE

          for binary in dist/*; do
            filename=$(basename $binary)
            
            temp_dir=$(mktemp -d)
            
            # 复制文件到临时目录
            cp -v "$binary" "$temp_dir/"
            cp -rv static/ "$temp_dir/static/"
            cp -v README.md README-zh.md LICENSE NOTICE "$temp_dir/"

            # 打包并检查退出状态
            cd "$temp_dir"
            if ! zip -9 -r "$GITHUB_WORKSPACE/dist/${filename%.*}.zip" *; then
              echo "打包失败: $filename"
              exit 1
            fi

            cd "$GITHUB_WORKSPACE"
            rm -rf "$temp_dir"
          done

          # 验证结果
          echo "=== 最终文件列表 ==="
          ls -l dist/
          echo "=== 压缩包验证 ==="
          for zipfile in dist/*.zip; do
            echo "验证 $zipfile:"
            unzip -tq "$zipfile" || exit 1
          done

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            dist/*.zip
