name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build application
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/ollamalens-linux-amd64 main.go
          GOOS=darwin GOARCH=arm64 go build -o dist/ollamalens-macos-arm64 main.go
          GOOS=windows GOARCH=amd64 go build -o dist/ollamalens-windows-amd64.exe main.go

      - name: Package artifacts
        run: |
          cd $GITHUB_WORKSPACE
          mkdir -p dist/release

          for binary in dist/*; do
            filename=$(basename $binary)
            
            # 创建临时目录并组织文件结构
            temp_dir=$(mktemp -d)
            cp "$binary" "$temp_dir/"
            cp -r static "$temp_dir/"
            cp README*.md LICENSE NOTICE "$temp_dir/"
            
            # 在临时目录中打包
            cd "$temp_dir"
            zip -r "$GITHUB_WORKSPACE/dist/release/${filename%.*}.zip" *
            cd "$GITHUB_WORKSPACE"
            rm -rf "$temp_dir"
          done

          # 验证打包结果
          ls -l dist/release/*.zip
          unzip -l dist/release/*.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            dist/release/*.zip
